//! DO NOT EDIT
//! Configuration options for zig-analyzer.
//! If you want to add a config option edit
//! tools/config_gen/config.json
//! GENERATED BY tools/config_gen/main.zig

/// Enables snippet completions when the client also supports them.
enable_snippets: bool = true,

/// Whether to enable function argument placeholder completions.
enable_argument_placeholders: bool = true,

/// Whether to show the function signature in completion results. May improve readability in some editors when disabled.
completion_label_details: bool = true,

/// Whether to enable build-on-save diagnostics. When unset, enabled automatically if `build.zig` declares a `check` step.
enable_build_on_save: ?bool = null,

/// Extra arguments passed to `zig build` for build-on-save. If `build.zig` declares a `check` step, that step is preferred over `install`.
build_on_save_args: []const []const u8 = &.{},

/// Semantic token detail level. `partial` only includes information that requires semantic analysis.
semantic_tokens: enum {
    none,
    partial,
    full,
} = .full,

/// Show inferred-type inlay hints for const/var declarations.
inlay_hints_show_variable_type_hints: bool = true,

/// Show inlay hints for fields in struct and union literals.
inlay_hints_show_struct_literal_field_type: bool = true,

/// Show parameter-name inlay hints at call sites.
inlay_hints_show_parameter_name: bool = true,

/// Show inlay hints for builtin functions.
inlay_hints_show_builtin: bool = true,

/// Omit parameter-name inlay hints for calls with exactly one argument.
inlay_hints_exclude_single_argument: bool = true,

/// Hide inlay hints when the parameter name matches the identifier (e.g. `foo: foo`).
inlay_hints_hide_redundant_param_names: bool = false,

/// Hide inlay hints when the parameter name matches the last token of a parameter node (e.g. `foo: bar.foo`).
inlay_hints_hide_redundant_param_names_last_token: bool = false,

/// Whether the language server provides document formatting. When disabled, Format Document is a no-op from the server.
enable_formatting: bool = true,

/// Executable of a stdin/stdout formatter. When unset, the built-in formatter (matching `zig fmt`) is used. Must read the entire document from stdin and write the fully formatted result to stdout.
formatter_command: ?[]const u8 = null,

/// Arguments passed to `formatter_command`. For `zig fmt`, use `["fmt", "--stdin"]`. Ignored when `formatter_command` is unset.
formatter_args: []const []const u8 = &.{},

/// Show reference counts as code lenses on declarations within the build-graph compilation unit.
enable_reference_code_lenses: bool = true,

/// Report unused private declarations as faded (Unnecessary) diagnostics. Public declarations are never reported.
enable_unused_decl_diagnostics: bool = true,

/// Report identifiers that don't follow the Zig naming conventions (camelCase functions, PascalCase types, snake_case constants/fields/namespaces) as hint diagnostics. Reuses docent's `identifier_case` rule.
enable_naming_convention_diagnostics: bool = true,

/// Prefer running `zig ast-check` as a child process instead of the built-in AstGen path.
prefer_ast_check_as_child_process: bool = true,

/// Override the path to the `builtin` module. Automatically resolved if unset.
builtin_path: ?[]const u8 = null,

/// Override the Zig library path. Automatically resolved from `zig_exe_path` when unset.
zig_lib_path: ?[]const u8 = null,

/// Path to the Zig executable (not the directory). If unset, `zig` is looked up in `PATH`.
zig_exe_path: ?[]const u8 = null,

/// Custom build runner used to resolve build system information.
build_runner_path: ?[]const u8 = null,

/// Directory used as Zig's cache. Defaults to `${KnownFolders.Cache}/zig-analyzer`.
global_cache_path: ?[]const u8 = null,

// DO NOT EDIT
