//! This script takes care of the following tasks:
//!
//! - generate `src/Config.zig`
//! - generate `schema.json`
//! - generate metadata about Zig's builtins (uses `src/tools/langref.html.in`)
//! - generate ZLS configuration options for vscode-zig's package.json
// TODO: This should be moved to /tools/config_gen/main.zig and adjusted accordingly.
const std = @import("std");

const ConfigOption = struct {
    /// Name of config option
    name: []const u8,
    /// (used in doc comments & schema.json)
    description: []const u8,
    /// zig type in string form. e.g "u32", "[]const u8", "?usize"
    type: []const u8,
    /// if the zig type should be an enum, this should contain
    /// a list of enum values and `type`
    /// If this is set, the value `type` should to be `enum`
    @"enum": ?[]const []const u8 = null,
    /// used in Config.zig as the default initializer
    default: std.json.Value,

    fn getTypescriptType(self: ConfigOption) error{UnsupportedType}![]const u8 {
        std.debug.assert(self.type.len != 0);
        const ty = self.type[@intFromBool(self.type[0] == '?')..];
        return if (std.mem.eql(u8, ty, "[]const []const u8"))
            "array"
        else if (std.mem.eql(u8, ty, "[]const u8"))
            "string"
        else if (std.mem.eql(u8, ty, "bool"))
            "boolean"
        else if (std.mem.eql(u8, ty, "usize"))
            "integer"
        else if (std.mem.eql(u8, ty, "enum"))
            "string"
        else
            error.UnsupportedType;
    }

    fn formatZigType(config: ConfigOption, writer: *std.Io.Writer) std.Io.Writer.Error!void {
        if (config.@"enum") |enum_members| {
            try writer.writeAll("enum {\n");
            for (enum_members) |member_name| {
                try writer.print("    {s},\n", .{member_name});
            }
            std.debug.assert(enum_members.len > 1);
            try writer.writeByte('}');
            return;
        }
        try writer.writeAll(config.type);
    }

    fn fmtZigType(self: ConfigOption) std.fmt.Alt(ConfigOption, formatZigType) {
        return .{ .data = self };
    }

    fn formatDefaultValue(config: ConfigOption, writer: *std.Io.Writer) std.Io.Writer.Error!void {
        if (config.default == .array) {
            try writer.writeAll("&.{");
            for (config.default.array.items, 0..) |item, i| {
                if (i != 0) try writer.writeByte(',');
                std.json.Stringify.value(item, .{}, writer) catch |err| return @errorCast(err);
            }
            try writer.writeByte('}');
            return;
        }
        if (config.@"enum" != null) {
            try writer.print(".{s}", .{config.default.string});
            return;
        }
        std.json.Stringify.value(config.default, .{}, writer) catch |err| return @errorCast(err);
    }

    fn fmtDefaultValue(self: ConfigOption) std.fmt.Alt(ConfigOption, formatDefaultValue) {
        return .{ .data = self };
    }
};

const Config = struct {
    options: []ConfigOption,
};

const Schema = struct {
    @"$schema": []const u8 = "http://json-schema.org/draft-04/schema",
    title: []const u8 = "ZLS Config",
    description: []const u8 = "Configuration file for ZLS",
    type: []const u8 = "object",
    properties: std.json.ArrayHashMap(SchemaEntry),
};

const SchemaEntry = struct {
    description: []const u8,
    type: []const u8,
    items: ?struct { type: []const u8 } = null,
    @"enum": ?[]const []const u8 = null,
    default: std.json.Value,
};

const FormatDocs = struct {
    text: []const u8,
    comment_kind: CommentKind,

    const CommentKind = enum {
        normal,
        doc,
        top_level,
    };

    fn render(ctx: FormatDocs, writer: *std.Io.Writer) std.Io.Writer.Error!void {
        const prefix = switch (ctx.comment_kind) {
            .normal => "// ",
            .doc => "/// ",
            .top_level => "//! ",
        };
        var i: usize = 0;
        var iterator = std.mem.splitScalar(u8, ctx.text, '\n');
        while (iterator.next()) |line| : (i += 1) {
            if (i != 0) try writer.writeByte('\n');
            try writer.print("{s}{s}", .{ prefix, line });
        }
    }
};

fn fmtDocs(text: []const u8, comment_kind: FormatDocs.CommentKind) std.fmt.Alt(FormatDocs, FormatDocs.render) {
    return .{ .data = .{ .text = text, .comment_kind = comment_kind } };
}

fn generateConfigFile(
    io: std.Io,
    allocator: std.mem.Allocator,
    config: Config,
    path: []const u8,
) (std.Io.Dir.WriteFileError || std.mem.Allocator.Error)!void {
    var aw: std.Io.Writer.Allocating = .init(allocator);
    defer aw.deinit();

    aw.writer.writeAll(
        \\//! DO NOT EDIT
        \\//! Configuration options for ZLS.
        \\//! If you want to add a config option edit
        \\//! src/tools/config.json
        \\//! GENERATED BY src/tools/config_gen.zig
        \\
    ) catch return error.OutOfMemory;

    for (config.options) |option| {
        aw.writer.print(
            \\
            \\{f}
            \\{f}: {f} = {f},
            \\
        , .{
            fmtDocs(std.mem.trim(u8, option.description, &std.ascii.whitespace), .doc),
            std.zig.fmtId(std.mem.trim(u8, option.name, &std.ascii.whitespace)),
            option.fmtZigType(),
            option.fmtDefaultValue(),
        }) catch return error.OutOfMemory;
    }

    aw.writer.writeAll(
        \\
        \\// DO NOT EDIT
        \\
    ) catch return error.OutOfMemory;

    const source_unformatted = try aw.toOwnedSliceSentinel(0);
    defer allocator.free(source_unformatted);

    var tree: std.zig.Ast = try .parse(allocator, source_unformatted, .zig);
    defer tree.deinit(allocator);
    std.debug.assert(tree.errors.len == 0);

    const source = try tree.renderAlloc(allocator);
    defer allocator.free(source);

    try std.Io.Dir.cwd().writeFile(io, .{
        .sub_path = path,
        .data = source,
    });
}

fn generateSchemaFile(
    io: std.Io,
    allocator: std.mem.Allocator,
    config: Config,
    path: []const u8,
) !void {
    const schema_file = try std.Io.Dir.cwd().createFile(io, path, .{});
    defer schema_file.close(io);

    var buffer: [4096]u8 = undefined;
    var file_writer = schema_file.writer(io, &buffer);
    const writer = &file_writer.interface;

    var schema: Schema = .{ .properties = .{} };
    defer schema.properties.map.deinit(allocator);

    try schema.properties.map.ensureTotalCapacity(allocator, @intCast(config.options.len));

    for (config.options) |option| {
        schema.properties.map.putAssumeCapacityNoClobber(option.name, .{
            .description = option.description,
            .type = try option.getTypescriptType(),
            .items = if (std.mem.eql(u8, option.type, "[]const []const u8")) .{ .type = "string" } else null,
            .@"enum" = option.@"enum",
            .default = option.default,
        });
    }

    try std.json.Stringify.value(schema, .{
        .whitespace = .indent_4,
        .emit_null_optional_fields = false,
    }, writer);

    try writer.writeByte('\n');
    try file_writer.end();
}

const ConfigurationProperty = struct {
    scope: []const u8 = "resource",
    type: []const u8,
    description: []const u8,
    @"enum": ?[]const []const u8 = null,
    format: ?[]const u8 = null,
    default: ?std.json.Value = null,
};

fn generateVSCodeConfigFile(
    io: std.Io,
    allocator: std.mem.Allocator,
    config: Config,
    path: []const u8,
) !void {
    var config_file = try std.Io.Dir.cwd().createFile(io, path, .{});
    defer config_file.close(io);

    const predefined_configurations: usize = 4;
    var configuration: std.json.ArrayHashMap(ConfigurationProperty) = .{};
    try configuration.map.ensureTotalCapacity(allocator, @intCast(predefined_configurations + config.options.len));
    defer {
        for (configuration.map.keys()[predefined_configurations..]) |name| allocator.free(name);
        configuration.map.deinit(allocator);
    }

    configuration.map.putAssumeCapacityNoClobber("zig.zls.debugLog", .{
        .scope = "resource",
        .type = "boolean",
        .description = "Enable debug logging in release builds of ZLS.",
    });
    configuration.map.putAssumeCapacityNoClobber("zig.zls.trace.server", .{
        .scope = "window",
        .type = "string",
        .@"enum" = &.{ "off", "messages", "verbose" },
        .description = "Traces the communication between VS Code and the language server.",
        .default = .{ .string = "off" },
    });
    configuration.map.putAssumeCapacityNoClobber("zig.zls.path", .{
        .scope = "machine-overridable",
        .type = "string",
        .description = "Path to `zls` executable. Example: `C:/zls/zig-cache/bin/zls.exe`. The string \"zls\" means lookup ZLS in PATH.",
        .format = "path",
    });

    for (config.options) |option| {
        if (std.mem.eql(u8, option.name, "zig_exe_path")) continue; // vscode-zig has its own option for this
        if (std.mem.eql(u8, option.name, "force_autofix")) continue; // VS Code supports code actions on save without a workaround

        const snake_case_name = try std.fmt.allocPrint(allocator, "zig.zls.{s}", .{option.name});
        defer allocator.free(snake_case_name);
        const name = try snakeCaseToCamelCase(allocator, snake_case_name);
        errdefer allocator.free(name);

        const default: ?std.json.Value = if (std.mem.eql(u8, option.name, "enable_build_on_save"))
            // "enable_build_on_save" need to be explicitly set to 'null' so that it doesn't default to 'false'
            .null
        else if (option.default != .null)
            option.default
        else
            null;

        configuration.map.putAssumeCapacityNoClobber(name, .{
            .type = try option.getTypescriptType(),
            .description = option.description,
            .@"enum" = option.@"enum",
            .format = if (std.mem.find(u8, option.name, "path") != null) "path" else null,
            .default = default,
        });
    }

    var buffer: [4096]u8 = undefined;
    var file_writer = config_file.writer(io, &buffer);
    const writer = &file_writer.interface;

    try std.json.Stringify.value(configuration, .{
        .whitespace = .indent_2,
        .emit_null_optional_fields = false,
    }, writer);
    try file_writer.end();
}

fn snakeCaseToCamelCase(allocator: std.mem.Allocator, str: []const u8) error{OutOfMemory}![]u8 {
    const underscore_count = std.mem.count(u8, str, "_");
    var result = try allocator.alloc(u8, str.len - underscore_count);
    var i: usize = 0;
    var j: usize = 0;
    while (i < str.len) : (i += 1) {
        if (str[i] != '_') {
            result[j] = str[i];
            j += 1;
            continue;
        }
        if (i + 1 < str.len and 'a' <= str[i + 1] and str[i + 1] <= 'z') {
            result[j] = std.ascii.toUpper(str[i + 1]);
            i += 1;
            j += 1;
        }
    }
    return result;
}

/// Tokenizer for a langref.html.in file
/// example file: https://raw.githubusercontent.com/ziglang/zig/master/doc/langref.html.in
/// this is a modified version from https://github.com/ziglang/zig/blob/master/doc/docgen.zig
const Tokenizer = struct {
    buffer: []const u8,
    index: usize = 0,
    state: State = .Start,

    const State = enum {
        Start,
        LBracket,
        Hash,
        TagName,
        Eof,
    };

    const Token = struct {
        id: Id,
        start: usize,
        end: usize,

        const Id = enum {
            Invalid,
            Content,
            BracketOpen,
            TagContent,
            Separator,
            BracketClose,
            Eof,
        };
    };

    fn next(self: *Tokenizer) Token {
        var result: Token = .{
            .id = .Eof,
            .start = self.index,
            .end = undefined,
        };
        while (self.index < self.buffer.len) : (self.index += 1) {
            const c = self.buffer[self.index];
            switch (self.state) {
                .Start => switch (c) {
                    '{' => {
                        self.state = .LBracket;
                    },
                    else => {
                        result.id = .Content;
                    },
                },
                .LBracket => switch (c) {
                    '#' => {
                        if (result.id != .Eof) {
                            self.index -= 1;
                            self.state = .Start;
                            break;
                        } else {
                            result.id = .BracketOpen;
                            self.index += 1;
                            self.state = .TagName;
                            break;
                        }
                    },
                    else => {
                        result.id = .Content;
                        self.state = .Start;
                    },
                },
                .TagName => switch (c) {
                    '|' => {
                        if (result.id != .Eof) {
                            break;
                        } else {
                            result.id = .Separator;
                            self.index += 1;
                            break;
                        }
                    },
                    '#' => {
                        self.state = .Hash;
                    },
                    else => {
                        result.id = .TagContent;
                    },
                },
                .Hash => switch (c) {
                    '}' => {
                        if (result.id != .Eof) {
                            self.index -= 1;
                            self.state = .TagName;
                            break;
                        } else {
                            result.id = .BracketClose;
                            self.index += 1;
                            self.state = .Start;
                            break;
                        }
                    },
                    else => {
                        result.id = .TagContent;
                        self.state = .TagName;
                    },
                },
                .Eof => unreachable,
            }
        } else {
            switch (self.state) {
                .Start,
                .LBracket,
                .Eof,
                => {},
                else => {
                    result.id = .Invalid;
                },
            }
            self.state = .Eof;
        }
        result.end = self.index;
        return result;
    }
};

const Builtin = struct {
    name: []const u8,
    signature: []const u8,
};

/// Parses a `langref.html.in` file and extracts the name and signature of every builtin
/// function documented in this section: `https://ziglang.org/documentation/master/#Builtin-Functions`
///
/// The prose documentation for each builtin is intentionally not collected here; hover/completion
/// documentation is instead a generated link to the online Language Reference (see `TODO.md`).
fn collectBuiltinData(allocator: std.mem.Allocator, langref_file: []const u8) error{OutOfMemory}![]Builtin {
    var tokenizer: Tokenizer = .{ .buffer = langref_file };

    const State = enum {
        /// searching for this line:
        /// {#header_open|Builtin Functions|2col#}
        searching,
        /// skippig builtin functions description:
        /// Builtin functions are provided by the compiler and are prefixed ...
        prefix,
        /// every entry begins with this:
        /// {#syntax#}@addrSpaceCast(comptime addrspace: std.builtin.AddressSpace, ptr: anytype) anytype{#endsyntax#}
        builtin_begin,
        /// skipping over documentation prose until the next builtin or the end of the section
        builtin_content,
    };
    var state: State = .searching;

    var builtins: std.ArrayList(Builtin) = .empty;
    errdefer builtins.deinit(allocator);

    var depth: u32 = undefined;
    while (true) {
        const token = tokenizer.next();
        switch (token.id) {
            .Content => continue,
            .BracketOpen => {
                const tag_token = tokenizer.next();
                std.debug.assert(tag_token.id == .TagContent);
                const tag_name = tokenizer.buffer[tag_token.start..tag_token.end];

                if (std.mem.eql(u8, tag_name, "header_open")) {
                    std.debug.assert(tokenizer.next().id == .Separator);
                    const content_token = tokenizer.next();
                    std.debug.assert(tag_token.id == .TagContent);
                    const content_name = tokenizer.buffer[content_token.start..content_token.end];

                    switch (state) {
                        .searching => {
                            if (std.mem.eql(u8, content_name, "Builtin Functions")) {
                                state = .prefix;
                                depth = 0;
                            }
                        },
                        .prefix, .builtin_begin => {
                            state = .builtin_begin;
                            try builtins.append(allocator, .{
                                .name = content_name,
                                .signature = "",
                            });
                        },
                        .builtin_content => unreachable,
                    }
                    if (state != .searching) {
                        depth += 1;
                    }

                    while (true) {
                        const bracket_tok = tokenizer.next();
                        switch (bracket_tok.id) {
                            .BracketClose => break,
                            .Separator, .TagContent => continue,
                            else => unreachable,
                        }
                    }
                } else if (std.mem.eql(u8, tag_name, "header_close")) {
                    std.debug.assert(tokenizer.next().id == .BracketClose);

                    if (state == .builtin_content) {
                        state = .builtin_begin;
                    }
                    if (state != .searching) {
                        depth -= 1;
                        if (depth == 0) break;
                    }
                } else if (state == .builtin_begin and std.mem.eql(u8, tag_name, "syntax")) {
                    std.debug.assert(tokenizer.next().id == .BracketClose);
                    const content_tag = tokenizer.next();
                    std.debug.assert(content_tag.id == .Content);
                    const content_name = tokenizer.buffer[content_tag.start..content_tag.end];
                    std.debug.assert(tokenizer.next().id == .BracketOpen);
                    const end_syntax_tag = tokenizer.next();
                    std.debug.assert(end_syntax_tag.id == .TagContent);
                    const end_tag_name = tokenizer.buffer[end_syntax_tag.start..end_syntax_tag.end];
                    std.debug.assert(std.mem.eql(u8, end_tag_name, "endsyntax"));
                    std.debug.assert(tokenizer.next().id == .BracketClose);

                    builtins.items[builtins.items.len - 1].signature = content_name;
                    state = .builtin_content;
                } else {
                    while (true) {
                        switch (tokenizer.next().id) {
                            .Eof => unreachable,
                            .BracketClose => break,
                            else => continue,
                        }
                    }
                }
            },
            else => unreachable,
        }
    }

    return try builtins.toOwnedSlice(allocator);
}

const Parameter = struct {
    signature: []const u8,
};

/// takes in a signature (without name or leading parenthesis) like this:
/// `comptime DestType: type, integer: anytype) DestType`
/// and outputs its parameters and return type:
/// `comptime DestType: type`, `integer: anytype`, `DestType`
fn extractParametersAndReturnTypeFromSignature(allocator: std.mem.Allocator, signature: [:0]const u8) error{OutOfMemory}!struct { []Parameter, []const u8 } {
    var parameters: std.ArrayList(Parameter) = .empty;
    errdefer parameters.deinit(allocator);

    var tokenizer: std.zig.Tokenizer = .init(signature);
    var argument_start: ?usize = null;
    while (true) {
        const token = tokenizer.next();
        switch (token.tag) {
            .eof => unreachable,
            .l_paren => {
                var paren_depth: usize = 1;
                while (paren_depth > 0) {
                    switch (tokenizer.next().tag) {
                        .l_paren => paren_depth += 1,
                        .r_paren => paren_depth -= 1,
                        else => {},
                    }
                }
                continue;
            },
            .comma, .r_paren => |tag| {
                if (argument_start) |start| {
                    try parameters.append(allocator, .{
                        .signature = std.mem.trim(u8, signature[start..token.loc.start], &std.ascii.whitespace),
                    });
                }
                argument_start = null;
                if (tag == .r_paren) break;
            },
            else => {
                if (argument_start == null) {
                    argument_start = token.loc.start;
                }
            },
        }
    }

    const return_type = signature[tokenizer.index + 1 ..];
    return .{ try parameters.toOwnedSlice(allocator), return_type };
}

/// Generates a data file describing the name, parameters, and return type of every builtin
/// function documented in the Zig Language Reference (https://ziglang.org/documentation/master/).
///
/// Prose documentation is deliberately not embedded here: hover/completion/signature-help
/// documentation for builtins is rendered as a link to the online Language Reference instead
/// (see `Analyser.renderBuiltinFunctionDocumentationLink`).
fn generateVersionDataFile(
    io: std.Io,
    allocator: std.mem.Allocator,
    output_path: []const u8,
    langref_path: []const u8,
) !void {
    const langref_source = try std.Io.Dir.cwd().readFileAlloc(io, langref_path, allocator, .limited(16 * 1024 * 1024));
    defer allocator.free(langref_source);

    const builtins = try collectBuiltinData(allocator, langref_source);
    defer allocator.free(builtins);

    var builtin_file = try std.Io.Dir.cwd().createFile(io, output_path, .{});
    defer builtin_file.close(io);

    var buffer: [4096]u8 = undefined;
    var file_writer = builtin_file.writer(io, &buffer);
    const writer = &file_writer.interface;

    try writer.writeAll(
        \\//! DO NOT EDIT
        \\//! GENERATED BY src/tools/config_gen.zig
        \\
        \\const std = @import("std");
        \\
        \\pub const Builtin = struct {
        \\    return_type: []const u8,
        \\    parameters: []const Parameter,
        \\
        \\    pub const Parameter = struct {
        \\        signature: []const u8,
        \\    };
        \\};
        \\
        \\pub const builtins: std.StaticStringMap(Builtin) = .initComptime(&[_]struct { []const u8, Builtin }{
        \\
    );

    for (builtins) |builtin| {
        const signature0 = builtin.signature[builtin.name.len + 1 ..];
        const signature1 = try std.mem.replaceOwned(u8, allocator, signature0, "std.builtin.", "");
        defer allocator.free(signature1);
        const signature2 = try std.mem.replaceOwned(u8, allocator, signature1, "builtin.", "");
        defer allocator.free(signature2);
        const signature_with_sentinel = try allocator.dupeSentinel(u8, signature2, 0);
        defer allocator.free(signature_with_sentinel);

        const parameters, const return_type = try extractParametersAndReturnTypeFromSignature(allocator, signature_with_sentinel);
        defer allocator.free(parameters);

        try writer.print(
            \\    .{{
            \\        "{f}",
            \\        .{{
            \\            .return_type = "{f}",
            \\            .parameters = &.{{
            \\
        , .{
            std.zig.fmtString(builtin.name),
            std.zig.fmtString(return_type),
        });

        for (parameters) |param| {
            try writer.print(
                \\                .{{ .signature = "{f}" }},
                \\
            , .{std.zig.fmtString(param.signature)});
        }

        try writer.writeAll(
            \\            },
            \\        },
            \\    },
            \\
        );
    }

    try writer.writeAll(
        \\});
        \\
        \\// DO NOT EDIT
        \\
    );
    try file_writer.end();
}

pub fn main(init: std.process.Init.Minimal) !void {
    var debug_allocator: std.heap.DebugAllocator(.{}) = .init;
    defer _ = debug_allocator.deinit();
    const gpa = debug_allocator.allocator();

    var threaded: std.Io.Threaded = .init_single_threaded;
    const io = threaded.io();

    var args_it = try init.args.iterateAllocator(gpa);
    defer args_it.deinit();
    _ = args_it.skip();

    var config_path: ?[]const u8 = null;
    var schema_path: ?[]const u8 = null;
    var vscode_config_path: ?[]const u8 = null;
    var version_data_path: ?[]const u8 = null;
    var langref_path: ?[]const u8 = null;

    while (args_it.next()) |argname| {
        if (std.mem.eql(u8, argname, "--help")) {
            try std.Io.File.stdout().writeStreamingAll(io,
                \\Usage: zig build gen -- [command]
                \\
                \\Commands:
                \\  --help                           Prints this message
                \\  --generate-vscode-config [path]  Output zls-vscode configurations
                \\  --generate-config [path]         Output path to config file (see src/Config.zig)
                \\  --generate-schema [path]         Output json schema file (see schema.json)
                \\  --generate-version-data [path]   Output data file
                \\  --langref-path [path]            Input langref.html.in file path
                \\
            );
            return std.process.cleanExit(io);
        } else if (std.mem.eql(u8, argname, "--generate-config")) {
            config_path = args_it.next() orelse {
                std.process.fatal("Expected output path after --generate-config argument.\n", .{});
            };
        } else if (std.mem.eql(u8, argname, "--generate-schema")) {
            schema_path = args_it.next() orelse {
                std.process.fatal("Expected output path after --generate-schema argument.\n", .{});
            };
        } else if (std.mem.eql(u8, argname, "--generate-vscode-config")) {
            vscode_config_path = args_it.next() orelse {
                std.process.fatal("Expected output path after --generate-vscode-config argument.\n", .{});
            };
        } else if (std.mem.eql(u8, argname, "--generate-version-data")) {
            version_data_path = args_it.next() orelse {
                std.process.fatal("Expected output path after --generate-version-data argument.\n", .{});
            };
        } else if (std.mem.eql(u8, argname, "--langref-path")) {
            langref_path = args_it.next() orelse {
                std.process.fatal("Expected output path after --langref-path argument.\n", .{});
            };
        } else {
            std.process.fatal("Unrecognized argument '{s}'.\n", .{argname});
        }
    }

    const config_json = try std.json.parseFromSlice(Config, gpa, @embedFile("config.json"), .{});
    defer config_json.deinit();
    const config = config_json.value;

    if (config_path) |output_path| {
        try generateConfigFile(io, gpa, config, output_path);
    }
    if (schema_path) |output_path| {
        try generateSchemaFile(io, gpa, config, output_path);
    }
    if (vscode_config_path) |output_path| {
        try generateVSCodeConfigFile(io, gpa, config, output_path);
        try std.Io.File.stderr().writeStreamingAll(io,
            \\Changing configuration options may also require editing the `package.json` from ziglang/vscode-zig at https://github.com/ziglang/vscode-zig/blob/master/package.json
            \\You can use `zig build gen -- --vscode-config-path /path/to/output/file.json` to generate the new configuration properties which you can then copy into `package.json`
            \\
        );
    }
    if (version_data_path) |output_path| {
        try generateVersionDataFile(
            io,
            gpa,
            output_path,
            langref_path orelse std.process.fatal("--generate-version-data requires --langref-path to be specified", .{}),
        );
    }
}
